### PR TITLE
Update my_quadprog.py

### PR DESCRIPTION
**Pull request by dmeoli**

### CODE REVIEW

**Review by berty38 — COMMENTED** [review]
Did I have this clipping backwards? I don't remember the status of my implementation—was it not properly handling inequality constraints?

**Comment by dmeoli** [comment]
@berty38 simply because the Lagrange multipliers which control the inequality constraints are in turn constrained to be >= 0; so `a_min` needs to be 0 while `a_max` is free :)

**Comment by berty38** [comment]
Can you check it again? It looks to me that when violations is positive, it's good (it satisfies coeffs.T.dot(x) >= constants). So we should clip away the positive elements. I wrote it as a greater-than constraint to match the definition of quadprog (https://pypi.org/project/quadprog/). 

You might still be right. I make sign errors all the time. The good thing about sign errors is if you make two, they disappear.

**Comment by dmeoli** [comment]
Oh sorry, I was considering the QP in its standard quadratic form, i.e. x^T Q x + q^T x s.t. G x <= 0

**Comment by berty38** [comment]
Yeah, I would prefer that form, but I wanted to make it a drop-in replacement for quadprog, which for some reason is written with a greater-than constraint.

**Pull request closed without merging**
